version: 0.2

phases:
  install:
    commands:
      - echo "Install phase"
  pre_build:
    commands:
      - echo "Pre Build phase"
      - echo "Logging into Amazon ECR"
      - aws --version
      - docker info
      - $(aws ecr get-login --no-include-email --region ap-south-1 --registry-ids 267021221325)
      - REPOSITORY_URI=267021221325.dkr.ecr.ap-south-1.amazonaws.com/eurekaserver
  build:
    commands:
      - echo "Build phase"
      - echo "Building Docker image..."
      - docker build -t eurekaserver .
      - docker tag eurekaserver:latest 267021221325.dkr.ecr.ap-south-1.amazonaws.com/eurekaserver:latest
  post_build:
    commands:
      - echo "post_build phase"
      - docker push 267021221325.dkr.ecr.ap-south-1.amazonaws.com/eurekaserver:latest
      - printf '[{"name":"eurekaservice","imageUri":"%s"}]' 267021221325.dkr.ecr.ap-south-1.amazonaws.com/eurekaserver:latest > imagedefinitions.json
  
artifacts:
  files: imagedefinitions.json
